version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network

  airflow-webserver:
    build:
      context: ..
      dockerfile: docker/Dockerfile.airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://etl_user:etl_password@postgres:5432/etl_db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ../dags:/opt/airflow/dags
      - ../plugins:/opt/airflow/plugins
      - ../storage:/opt/airflow/storage
      - ../logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - etl_network

  airflow-scheduler:
    build:
      context: ..
      dockerfile: docker/Dockerfile.airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://etl_user:etl_password@postgres:5432/etl_db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ../dags:/opt/airflow/dags
      - ../plugins:/opt/airflow/plugins
      - ../storage:/opt/airflow/storage
      - ../logs:/opt/airflow/logs
    depends_on:
      - postgres
      - airflow-webserver
    networks:
      - etl_network

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: etl_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - etl_network

volumes:
  postgres_data:

networks:
  etl_network:
    driver: bridge
